# Generated by Django 4.1.2 on 2022-10-12 12:38

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelNoMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("view_stuff", "Can view stuff"),),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ModelUsesMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("view_stuff", "Can view stuff"),),
            },
            bases=(demo.models.ModelMixin, models.Model),
        ),
    ]
